Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,26 +1,34 @@
-name: Sync upstream
- 
+name: Upstream Sync
+
+permissions:
+    contents: write
+
 on:
-  schedule:
-    - cron: '0 0 * * *'  # 每天UTC时间0点执行
- 
+    schedule:
+        - cron: "0 0 * * *"
+    workflow_dispatch:
+
 jobs:
-  sync:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-          ref: main
-      - name: Configure git
-        run: |
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
-      - name: Add upstream repo
-        run: git remote add upstream https://github.com/amll-dev/amll-ttml-tool.git
-      - name: Fetch upstream
-        run: git fetch upstream
-      - name: Merge upstream
-        run: git merge upstream/main --allow-unrelated-histories
-      - name: Push changes
-        run: git push origin main
+    sync_with_upstream:
+        name: Sync with Upstream
+        runs-on: ubuntu-latest
+        if: ${{ github.event.repository.fork }}
+
+        steps:
+            - name: Checkout target repo
+              uses: actions/checkout@v3
+
+            - name: Sync Upstream
+              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+              with:
+                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
+                  upstream_sync_repo: HackJava/HackJava
+                  upstream_sync_branch: main
+                  target_sync_branch: main
+                  test_mode: false
+
+            - name: Check for Failure
+              if: failure()
+              run: |
+                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+                  exit 1
